map $uri $track_header {
    ~*(rpm|xml|txt)$ "true";
    default "";
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    location / {
        sendfile           on;
        sendfile_max_chunk 1m;

        alias /var/www/nowhere-to-be-found;
        proxy_set_header   x-track $track_header;
        proxy_set_header   x-sendfile-type     x-accel-redirect;
        proxy_set_header   X-Accel-Mapping     /files/=/files/;

        proxy_set_header Host $host:8080;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port 8080;
        proxy_pass http://rmt:4224;
    }
    
    location /files/ {
        alias /var/www;
        internal;
    }    
}
